package com.yinhang.api.mapper;

import com.yinhang.api.entity.Card;
import com.yinhang.api.entity.CardExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int countByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int deleteByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int insert(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int insertSelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    List<Card> selectByExample(CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    Card selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByExample(@Param("record") Card record, @Param("example") CardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByPrimaryKeySelective(Card record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_CARD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByPrimaryKey(Card record);
}