package com.yinhang.api.mapper;

import com.yinhang.api.entity.Loan;
import com.yinhang.api.entity.LoanExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LoanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int countByExample(LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int deleteByExample(LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int insert(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int insertSelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    List<Loan> selectByExample(LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    Loan selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByExampleSelective(@Param("record") Loan record, @Param("example") LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByExample(@Param("record") Loan record, @Param("example") LoanExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByPrimaryKeySelective(Loan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table YU_LOAN
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    int updateByPrimaryKey(Loan record);
}