package com.yinhang.api.mapper;

import com.yinhang.api.entity.LogTable;
import com.yinhang.api.entity.LogTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LogTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGTABLE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    int countByExample(LogTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGTABLE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    int deleteByExample(LogTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGTABLE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    int insert(LogTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGTABLE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    int insertSelective(LogTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGTABLE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    List<LogTable> selectByExample(LogTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGTABLE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    int updateByExampleSelective(@Param("record") LogTable record, @Param("example") LogTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LOGTABLE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    int updateByExample(@Param("record") LogTable record, @Param("example") LogTableExample example);
}