package com.yinhang.api.entity;

import java.math.BigDecimal;

public class Card {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_CARD.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_CARD.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_CARD.CARD_NUMBER
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_CARD.PASSWORD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_CARD.CARD_BALANCE
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private BigDecimal cardBalance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_CARD.ID
     *
     * @return the value of YU_CARD.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_CARD.ID
     *
     * @param id the value for YU_CARD.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_CARD.USERNAME
     *
     * @return the value of YU_CARD.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_CARD.USERNAME
     *
     * @param username the value for YU_CARD.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_CARD.CARD_NUMBER
     *
     * @return the value of YU_CARD.CARD_NUMBER
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_CARD.CARD_NUMBER
     *
     * @param cardNumber the value for YU_CARD.CARD_NUMBER
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_CARD.PASSWORD
     *
     * @return the value of YU_CARD.PASSWORD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_CARD.PASSWORD
     *
     * @param password the value for YU_CARD.PASSWORD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_CARD.CARD_BALANCE
     *
     * @return the value of YU_CARD.CARD_BALANCE
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public BigDecimal getCardBalance() {
        return cardBalance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_CARD.CARD_BALANCE
     *
     * @param cardBalance the value for YU_CARD.CARD_BALANCE
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setCardBalance(BigDecimal cardBalance) {
        this.cardBalance = cardBalance;
    }
}