package com.yinhang.api.entity;

import java.util.Date;

public class LogTable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGTABLE.LOG_DATE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    private Date logDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LOGTABLE.ACTION
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    private String action;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGTABLE.LOG_DATE
     *
     * @return the value of LOGTABLE.LOG_DATE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    public Date getLogDate() {
        return logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGTABLE.LOG_DATE
     *
     * @param logDate the value for LOGTABLE.LOG_DATE
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    public void setLogDate(Date logDate) {
        this.logDate = logDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LOGTABLE.ACTION
     *
     * @return the value of LOGTABLE.ACTION
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    public String getAction() {
        return action;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LOGTABLE.ACTION
     *
     * @param action the value for LOGTABLE.ACTION
     *
     * @mbggenerated Tue Dec 17 12:11:52 CST 2019
     */
    public void setAction(String action) {
        this.action = action == null ? null : action.trim();
    }
}