package com.yinhang.api.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Transaction {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_TRANSACTION.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_TRANSACTION.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_TRANSACTION.CARD_NUMBER
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String cardNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_TRANSACTION.AMOUNT
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_TRANSACTION.TYPE
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_TRANSACTION.CREATE_TIME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_TRANSACTION.ID
     *
     * @return the value of YU_TRANSACTION.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_TRANSACTION.ID
     *
     * @param id the value for YU_TRANSACTION.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_TRANSACTION.USERNAME
     *
     * @return the value of YU_TRANSACTION.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_TRANSACTION.USERNAME
     *
     * @param username the value for YU_TRANSACTION.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_TRANSACTION.CARD_NUMBER
     *
     * @return the value of YU_TRANSACTION.CARD_NUMBER
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getCardNumber() {
        return cardNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_TRANSACTION.CARD_NUMBER
     *
     * @param cardNumber the value for YU_TRANSACTION.CARD_NUMBER
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber == null ? null : cardNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_TRANSACTION.AMOUNT
     *
     * @return the value of YU_TRANSACTION.AMOUNT
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_TRANSACTION.AMOUNT
     *
     * @param amount the value for YU_TRANSACTION.AMOUNT
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_TRANSACTION.TYPE
     *
     * @return the value of YU_TRANSACTION.TYPE
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_TRANSACTION.TYPE
     *
     * @param type the value for YU_TRANSACTION.TYPE
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_TRANSACTION.CREATE_TIME
     *
     * @return the value of YU_TRANSACTION.CREATE_TIME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_TRANSACTION.CREATE_TIME
     *
     * @param createTime the value for YU_TRANSACTION.CREATE_TIME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}