package com.yinhang.api.entity;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_USER.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_USER.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YU_USER.PASSWORD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_USER.ID
     *
     * @return the value of YU_USER.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_USER.ID
     *
     * @param id the value for YU_USER.ID
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_USER.USERNAME
     *
     * @return the value of YU_USER.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_USER.USERNAME
     *
     * @param username the value for YU_USER.USERNAME
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YU_USER.PASSWORD
     *
     * @return the value of YU_USER.PASSWORD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YU_USER.PASSWORD
     *
     * @param password the value for YU_USER.PASSWORD
     *
     * @mbggenerated Mon Dec 16 21:28:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}